/**
 * AUTO-GENERATED by gen-moons.mjs — DO NOT EDIT (run `npm run gen:moons`).
 * Generated 2026-06-10 from https://ssd.jpl.nasa.gov/sats/elem/ (geometry, frames, quoted
 * periods; the quoted source strings are preserved verbatim in each
 * record's comment) and JPL Horizons vectors (anchored mean anomaly at
 * epoch; calibrated/fitted rates).
 *
 * Model: omega(t) = omega0 + omegaDot*dt, node(t) = node0 + nodeDot*dt,
 * M(t) = anchoredM0 + mDot*dt; dt in days TT from epochJdTdb (TT~TDB).
 *
 * Tiers (each record's comment carries its quoted source values and the
 * selected model/signs so calibration choices stay reviewable):
 *  - verbatim: rates derive from the quoted periods via the selected
 *    semantics (the page is inconsistent about what P means).
 *  - fitted: quoted rates failed against Horizons (>6 deg max over the six
 *    base calibration epochs); rates least-squares fitted to those epochs,
 *    plus 12 dense ~3-yr-spaced epochs for moons flagged "dense" below
 *    (whole-revolution rate ambiguity). Geometry stays verbatim; residuals
 *    are maxima over the epochs each moon was actually fit on.
 *  - librator: resonant longitude libration (Mimas-Tethys, co-orbitals,
 *    trojans, Hyperion); no linear model can track it. Best-effort rates;
 *    expect tens of degrees of in-plane error.
 *
 * The `equatorial`-frame pole for Uranus rows is the ANTI-IAU pole
 * (angular-momentum pole, empirically resolved: Miranda 1.1 deg vs 116 deg).
 *
 * Validity: anchored/calibrated over 1990-2040; linear extrapolation
 * degrades gracefully outside (plane/ellipse stay sane, phase drifts).
 *
 * Per-moon max calibration / holdout-2026 residuals (deg):
 *   Phobos       fitted+dense   cal=   2.72 holdout=   1.41
 *   Deimos       fitted         cal=   2.21 holdout=   1.79
 *   Metis        fitted         cal=   0.09 holdout=   0.01
 *   Amalthea     fitted         cal=   0.44 holdout=   0.08
 *   Thebe        fitted         cal=   0.17 holdout=   0.19
 *   Io           verbatim       cal=   1.06 holdout=   0.71
 *   Europa       verbatim       cal=   2.35 holdout=   1.59
 *   Ganymede     verbatim       cal=   0.19 holdout=   0.16
 *   Callisto     verbatim       cal=   0.11 holdout=   0.09
 *   Himalia      fitted+dense   cal=  39.71 holdout=  16.67
 *   Lysithea     fitted+dense   cal=  20.67 holdout=  12.38
 *   Elara        fitted+dense   cal=  47.58 holdout=  35.17
 *   Ananke       fitted+dense   cal=  56.46 holdout=  26.61
 *   Carme        fitted+dense   cal=  54.42 holdout=  55.74
 *   Pasiphae     fitted+dense   cal=  76.82 holdout=  32.08
 *   Sinope       fitted+dense   cal=  48.83 holdout=  41.80
 *   Pan          verbatim       cal=   4.46 holdout=   2.95
 *   Atlas        fitted+dense   cal=  10.92 holdout=   1.06
 *   Prometheus   fitted+dense   cal=   8.18 holdout=   3.53
 *   Pandora      fitted+dense   cal=  11.33 holdout=   6.56
 *   Epimetheus   librator       cal=  38.73 holdout=   6.35
 *   Janus        librator       cal=  28.29 holdout=  13.88
 *   Mimas        librator       cal=  28.91 holdout=  25.90
 *   Enceladus    verbatim       cal=   0.64 holdout=   0.43
 *   Tethys       verbatim       cal=   2.68 holdout=   2.91
 *   Calypso      librator       cal=   4.50 holdout=   2.61
 *   Telesto      librator       cal=   2.66 holdout=   1.25
 *   Dione        verbatim       cal=   0.83 holdout=   0.79
 *   Helene       librator       cal=  15.03 holdout=  14.71
 *   Rhea         verbatim       cal=   0.55 holdout=   0.13
 *   Titan        verbatim       cal=   5.47 holdout=   4.08
 *   Hyperion     librator       cal=  23.01 holdout=  14.19
 *   Iapetus      verbatim       cal=   1.67 holdout=   1.27
 *   Phoebe       fitted+dense   cal=  21.28 holdout=   7.11
 *   Cordelia     fitted+dense   cal=   0.35 holdout=   0.19
 *   Ophelia      fitted+dense   cal=   2.16 holdout=   0.95
 *   Bianca       fitted+dense   cal=   4.43 holdout=   1.46
 *   Cressida     fitted+dense   cal=   3.05 holdout=   0.51
 *   Juliet       fitted+dense   cal=   2.42 holdout=   0.11
 *   Portia       fitted+dense   cal=   4.23 holdout=   0.37
 *   Rosalind     fitted+dense   cal=   2.72 holdout=   2.19
 *   Puck         fitted+dense   cal=   2.68 holdout=   1.52
 *   Miranda      verbatim       cal=   2.32 holdout=   0.38
 *   Ariel        verbatim       cal=   0.40 holdout=   0.46
 *   Umbriel      verbatim       cal=   0.17 holdout=   0.08
 *   Titania      verbatim       cal=   0.26 holdout=   0.08
 *   Oberon       verbatim       cal=   0.20 holdout=   0.18
 *   Caliban      fitted+dense   cal=  24.45 holdout=   2.97
 *   Sycorax      fitted         cal=   4.64 holdout=   5.50
 *   Naiad        fitted         cal=   0.42 holdout=   0.69
 *   Thalassa     verbatim       cal=   4.99 holdout=   3.34
 *   Despina      fitted         cal=   0.33 holdout=   0.24
 *   Galatea      fitted         cal=   0.31 holdout=   0.09
 *   Larissa      fitted         cal=   0.34 holdout=   0.06
 *   Proteus      verbatim       cal=   1.09 holdout=   0.75
 *   Triton       fitted         cal=   0.39 holdout=   0.25
 *   Nereid       verbatim       cal=   0.58 holdout=   0.41
 *   Halimede     fitted+dense   cal=  64.31 holdout=  35.94
 *   Neso         fitted+dense   cal=  90.43 holdout=  18.49
 *   Charon       verbatim       cal=   0.08 holdout=   0.08
 *   Styx         fitted+dense   cal=   9.58 holdout=   4.90
 *   Nix          fitted         cal=   4.61 holdout=   0.52
 *   Kerberos     fitted         cal=   4.85 holdout=   4.40
 *   Hydra        fitted         cal=   2.48 holdout=   0.37
 */

export interface SatelliteElementsRecord {
  parentPlanet: string;
  /** 'ecliptic' rows use the J2000 ecliptic; pole rows give the reference-plane pole (ICRF RA/Dec). */
  poleRaDeg: number | null;
  poleDecDeg: number | null;
  epochJdTdb: number;
  aKm: number;
  eccentricity: number;
  inclinationDeg: number;
  argPeriapsisAtEpochDeg: number;
  ascendingNodeAtEpochDeg: number;
  /** Horizons-anchored mean anomaly at epoch (the page phase columns are unreliable). */
  meanAnomalyAtEpochDeg: number;
  meanAnomalyRateDegPerDay: number;
  argPeriapsisRateDegPerDay: number;
  ascendingNodeRateDegPerDay: number;
  tier: 'verbatim' | 'fitted' | 'librator';
  /** Measured max angular separation vs Horizons over the calibration epochs (deg). */
  maxCalibrationSeparationDeg: number;
  /** Measured separation at the held-out 2026-06-11 epoch (deg). */
  holdoutSeparationDeg: number;
}

export const SATELLITE_ELEMENTS: Record<string, SatelliteElementsRecord> = {
  // MAR099 Laplace @ 2000-01-01.5; quoted: a=9375. e=0.015 ω=216.3 M=189.7 i=1.1 node=169.2 P=0.3187 Pap=1.1 Pnode=2.3 pole=(317.7,52.9) tilt=0.0
  // calibration: seed=anom signs=(+1,-1) dense-epochs
  "Phobos": {
    parentPlanet: "Mars",
    poleRaDeg: 317.7, poleDecDeg: 52.9,
    epochJdTdb: 2451545,
    aKm: 9375, eccentricity: 0.015, inclinationDeg: 1.1,
    argPeriapsisAtEpochDeg: 216.3, ascendingNodeAtEpochDeg: 169.2,
    meanAnomalyAtEpochDeg: 189.660033434,
    meanAnomalyRateDegPerDay: 1128.37935362412,
    argPeriapsisRateDegPerDay: 0.89442224121295,
    ascendingNodeRateDegPerDay: -0.428871237054254,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.723,
    holdoutSeparationDeg: 1.414,
  },
  // MAR099 Laplace @ 2000-01-01.5; quoted: a=23457. e=0.000 ω=0.0 M=205.0 i=1.8 node=54.3 P=1.2625 Pap=0.0 Pnode=56.2 pole=(316.6,53.5) tilt=0.9
  // calibration: seed=anom signs=(+1,+1)
  "Deimos": {
    parentPlanet: "Mars",
    poleRaDeg: 316.6, poleDecDeg: 53.5,
    epochJdTdb: 2451545,
    aKm: 23457, eccentricity: 0, inclinationDeg: 1.8,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 54.3,
    meanAnomalyAtEpochDeg: 205.095165536,
    meanAnomalyRateDegPerDay: 285.148514851485,
    argPeriapsisRateDegPerDay: 0.000269822429509871,
    ascendingNodeRateDegPerDay: 0.013087563783233,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.207,
    holdoutSeparationDeg: 1.793,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=128000. e=0.000 ω=0.0 M=166.0 i=0.0 node=0.0 P=0.294779 Pap=0.000 Pnode=0.000 pole=(268.1,64.5) tilt=0.0
  // calibration: seed=lam signs=(+1,-1)
  "Metis": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.1, poleDecDeg: 64.5,
    epochJdTdb: 2451545,
    aKm: 128000, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 165.93841358,
    meanAnomalyRateDegPerDay: 1221.2538885063,
    argPeriapsisRateDegPerDay: -0.0000980892,
    ascendingNodeRateDegPerDay: 0.0009010008,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.09472,
    holdoutSeparationDeg: 0.01043,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=181400. e=0.003 ω=180.1 M=310.6 i=0.4 node=282.9 P=0.499918 Pap=0.196 Pnode=0.393 pole=(268.1,64.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1)
  "Amalthea": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.1, poleDecDeg: 64.5,
    epochJdTdb: 2451545,
    aKm: 181400, eccentricity: 0.003, inclinationDeg: 0.4,
    argPeriapsisAtEpochDeg: 180.1, ascendingNodeAtEpochDeg: 282.9,
    meanAnomalyAtEpochDeg: 310.507925818,
    meanAnomalyRateDegPerDay: 720.118099368296,
    argPeriapsisRateDegPerDay: 5.02413447429074,
    ascendingNodeRateDegPerDay: -2.51051308393837,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.4371,
    holdoutSeparationDeg: 0.08071,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=221900. e=0.018 ω=26.6 M=182.1 i=1.1 node=340.4 P=0.676105 Pap=0.398 Pnode=0.797 pole=(268.1,64.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1)
  "Thebe": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.1, poleDecDeg: 64.5,
    epochJdTdb: 2451545,
    aKm: 221900, eccentricity: 0.018, inclinationDeg: 1.1,
    argPeriapsisAtEpochDeg: 26.6, ascendingNodeAtEpochDeg: 340.4,
    meanAnomalyAtEpochDeg: 182.043965681,
    meanAnomalyRateDegPerDay: 532.461673852434,
    argPeriapsisRateDegPerDay: 2.47590343685473,
    ascendingNodeRateDegPerDay: -1.23730060632197,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.1651,
    holdoutSeparationDeg: 0.1877,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=421800. e=0.004 ω=49.1 M=330.9 i=0.0 node=0.0 P=1.762732 Pap=1.333 Pnode=0.000 pole=(268.1,64.5) tilt=0.0
  // calibration: model=anom signs=(-1,-1)
  "Io": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.1, poleDecDeg: 64.5,
    epochJdTdb: 2451545,
    aKm: 421800, eccentricity: 0.004, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 49.1, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 330.797553898,
    meanAnomalyRateDegPerDay: 204.228436313631,
    argPeriapsisRateDegPerDay: -0.739404563666584,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 1.062,
    holdoutSeparationDeg: 0.7084,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=671100. e=0.009 ω=45.0 M=345.4 i=0.5 node=184.0 P=3.525463 Pap=1.394 Pnode=30.202 pole=(268.1,64.5) tilt=0.0
  // calibration: model=anom signs=(-1,-1)
  "Europa": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.1, poleDecDeg: 64.5,
    epochJdTdb: 2451545,
    aKm: 671100, eccentricity: 0.009, inclinationDeg: 0.5,
    argPeriapsisAtEpochDeg: 45, ascendingNodeAtEpochDeg: 184,
    meanAnomalyAtEpochDeg: 345.396235165,
    meanAnomalyRateDegPerDay: 102.114247121584,
    argPeriapsisRateDegPerDay: -0.707048983764388,
    ascendingNodeRateDegPerDay: -0.0326344706763644,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 2.355,
    holdoutSeparationDeg: 1.59,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=1070400. e=0.001 ω=198.3 M=324.8 i=0.2 node=58.5 P=7.155588 Pap=68.301 Pnode=137.812 pole=(268.2,64.6) tilt=0.1
  // calibration: model=anom signs=(+1,-1)
  "Ganymede": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.2, poleDecDeg: 64.6,
    epochJdTdb: 2451545,
    aKm: 1070400, eccentricity: 0.001, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 198.3, ascendingNodeAtEpochDeg: 58.5,
    meanAnomalyAtEpochDeg: 324.765818314,
    meanAnomalyRateDegPerDay: 50.3103308910463,
    argPeriapsisRateDegPerDay: 0.0144306274193285,
    ascendingNodeRateDegPerDay: -0.00715196269822335,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.1895,
    holdoutSeparationDeg: 0.1627,
  },
  // JUP365 Laplace @ 2000-01-01.5; quoted: a=1882700. e=0.007 ω=43.8 M=87.4 i=0.3 node=309.1 P=16.690440 Pap=277.921 Pnode=577.264 pole=(268.7,64.8) tilt=0.4
  // calibration: model=anom signs=(+1,-1)
  "Callisto": {
    parentPlanet: "Jupiter",
    poleRaDeg: 268.7, poleDecDeg: 64.8,
    epochJdTdb: 2451545,
    aKm: 1882700, eccentricity: 0.007, inclinationDeg: 0.3,
    argPeriapsisAtEpochDeg: 43.8, ascendingNodeAtEpochDeg: 309.1,
    meanAnomalyAtEpochDeg: 87.5242348703,
    meanAnomalyRateDegPerDay: 21.5692336451286,
    argPeriapsisRateDegPerDay: 0.00354642608283489,
    ascendingNodeRateDegPerDay: -0.00170740992573165,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.1135,
    holdoutSeparationDeg: 0.08917,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=11439000. e=0.160 ω=321.1 M=78.3 i=28.4 node=64.2 P=249.9090 Pap=187.4 Pnode=297.1 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,+1) dense-epochs
  "Himalia": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 11439000, eccentricity: 0.16, inclinationDeg: 28.4,
    argPeriapsisAtEpochDeg: 321.1, ascendingNodeAtEpochDeg: 64.2,
    meanAnomalyAtEpochDeg: 78.9796205522,
    meanAnomalyRateDegPerDay: 1.44037429624374,
    argPeriapsisRateDegPerDay: -0.00494414839116472,
    ascendingNodeRateDegPerDay: 0.00288262000623997,
    tier: "fitted",
    maxCalibrationSeparationDeg: 39.71,
    holdoutSeparationDeg: 16.67,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=11699100. e=0.117 ω=48.3 M=328.5 i=27.7 node=9.2 P=258.5035 Pap=178.9 Pnode=290.6 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,+1) dense-epochs
  "Lysithea": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 11699100, eccentricity: 0.117, inclinationDeg: 27.7,
    argPeriapsisAtEpochDeg: 48.3, ascendingNodeAtEpochDeg: 9.2,
    meanAnomalyAtEpochDeg: 327.163304529,
    meanAnomalyRateDegPerDay: 1.39340859988355,
    argPeriapsisRateDegPerDay: -0.0037455653263696,
    ascendingNodeRateDegPerDay: -0.000459262127424136,
    tier: "fitted",
    maxCalibrationSeparationDeg: 20.67,
    holdoutSeparationDeg: 12.38,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=11710700. e=0.212 ω=129.9 M=346.9 i=27.8 node=112.8 P=258.8861 Pap=173.0 Pnode=270.9 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,+1) dense-epochs
  "Elara": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 11710700, eccentricity: 0.212, inclinationDeg: 27.8,
    argPeriapsisAtEpochDeg: 129.9, ascendingNodeAtEpochDeg: 112.8,
    meanAnomalyAtEpochDeg: 346.616357877,
    meanAnomalyRateDegPerDay: 1.39127979447332,
    argPeriapsisRateDegPerDay: -0.00569162140746104,
    ascendingNodeRateDegPerDay: 0.00181716923490716,
    tier: "fitted",
    maxCalibrationSeparationDeg: 47.58,
    holdoutSeparationDeg: 35.17,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=21029500. e=0.238 ω=78.8 M=271.7 i=147.6 node=13.7 P=623.1097 Pap=80.8 Pnode=115.5 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Ananke": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 21029500, eccentricity: 0.238, inclinationDeg: 147.6,
    argPeriapsisAtEpochDeg: 78.8, ascendingNodeAtEpochDeg: 13.7,
    meanAnomalyAtEpochDeg: 255.007437548,
    meanAnomalyRateDegPerDay: 0.575872113690392,
    argPeriapsisRateDegPerDay: -0.0154544196516534,
    ascendingNodeRateDegPerDay: -0.0124850469330044,
    tier: "fitted",
    maxCalibrationSeparationDeg: 56.46,
    holdoutSeparationDeg: 26.61,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=23139200. e=0.261 ω=6.5 M=259.5 i=164.6 node=115.5 P=719.2806 Pap=50.9 Pnode=89.0 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Carme": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 23139200, eccentricity: 0.261, inclinationDeg: 164.6,
    argPeriapsisAtEpochDeg: 6.5, ascendingNodeAtEpochDeg: 115.5,
    meanAnomalyAtEpochDeg: 261.580905761,
    meanAnomalyRateDegPerDay: 0.502235149954041,
    argPeriapsisRateDegPerDay: -0.0193657362369828,
    ascendingNodeRateDegPerDay: -0.00553722132754945,
    tier: "fitted",
    maxCalibrationSeparationDeg: 54.42,
    holdoutSeparationDeg: 55.74,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=23463200. e=0.412 ω=172.8 M=279.3 i=148.3 node=315.7 P=734.4215 Pap=60.6 Pnode=79.2 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Pasiphae": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 23463200, eccentricity: 0.412, inclinationDeg: 148.3,
    argPeriapsisAtEpochDeg: 172.8, ascendingNodeAtEpochDeg: 315.7,
    meanAnomalyAtEpochDeg: 282.998094073,
    meanAnomalyRateDegPerDay: 0.492432479168917,
    argPeriapsisRateDegPerDay: -0.0162644454835611,
    ascendingNodeRateDegPerDay: -0.00622302221511294,
    tier: "fitted",
    maxCalibrationSeparationDeg: 76.82,
    holdoutSeparationDeg: 32.08,
  },
  // JUP347 ecliptic @ 2000-01-01.5; quoted: a=23679300. e=0.262 ω=354.3 M=157.4 i=157.3 node=308.0 P=744.5951 Pap=57.0 Pnode=93.1 pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Sinope": {
    parentPlanet: "Jupiter",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2451545,
    aKm: 23679300, eccentricity: 0.262, inclinationDeg: 157.3,
    argPeriapsisAtEpochDeg: 354.3, ascendingNodeAtEpochDeg: 308,
    meanAnomalyAtEpochDeg: 159.640481568,
    meanAnomalyRateDegPerDay: 0.484503591280703,
    argPeriapsisRateDegPerDay: -0.0172918620987788,
    ascendingNodeRateDegPerDay: -0.00529389298897522,
    tier: "fitted",
    maxCalibrationSeparationDeg: 48.83,
    holdoutSeparationDeg: 41.8,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=133600. e=0.000 ω=0.0 M=146.6 i=0.0 node=0.0 P=0.575051 Pap=0.000 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: model=lam signs=(+1,-1)
  "Pan": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 133600, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 146.573302041,
    meanAnomalyRateDegPerDay: 626.031430255751,
    argPeriapsisRateDegPerDay: 0,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 4.458,
    holdoutSeparationDeg: 2.946,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=137700. e=0.001 ω=82.3 M=289.1 i=0.0 node=0.0 P=0.604602 Pap=0.342 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1) dense-epochs
  "Atlas": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 137700, eccentricity: 0.001, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 82.3, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 290.675533995,
    meanAnomalyRateDegPerDay: 595.4330286701,
    argPeriapsisRateDegPerDay: 2.88194819698116,
    ascendingNodeRateDegPerDay: -0.0008647981,
    tier: "fitted",
    maxCalibrationSeparationDeg: 10.92,
    holdoutSeparationDeg: 1.064,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=139400. e=0.002 ω=341.9 M=135.4 i=0.0 node=0.0 P=0.615878 Pap=0.357 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1) dense-epochs
  "Prometheus": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 139400, eccentricity: 0.002, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 341.9, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 113.797145223,
    meanAnomalyRateDegPerDay: 584.526480893893,
    argPeriapsisRateDegPerDay: 2.7608579366038,
    ascendingNodeRateDegPerDay: -0.0010921061196415,
    tier: "fitted",
    maxCalibrationSeparationDeg: 8.18,
    holdoutSeparationDeg: 3.526,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=141700. e=0.004 ω=217.9 M=123.9 i=0.0 node=0.0 P=0.631369 Pap=0.379 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1) dense-epochs
  "Pandora": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 141700, eccentricity: 0.004, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 217.9, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 119.475432378,
    meanAnomalyRateDegPerDay: 570.187164716703,
    argPeriapsisRateDegPerDay: 2.60059705374025,
    ascendingNodeRateDegPerDay: -0.000700994499999999,
    tier: "fitted",
    maxCalibrationSeparationDeg: 11.33,
    holdoutSeparationDeg: 6.564,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=151400. e=0.020 ω=96.3 M=197.2 i=0.3 node=189.8 P=0.697012 Pap=0.240 Pnode=0.482 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=anom signs=(-1,+1)
  "Epimetheus": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 151400, eccentricity: 0.02, inclinationDeg: 0.3,
    argPeriapsisAtEpochDeg: 96.3, ascendingNodeAtEpochDeg: 189.8,
    meanAnomalyAtEpochDeg: 182.807581964,
    meanAnomalyRateDegPerDay: 516.490390409347,
    argPeriapsisRateDegPerDay: 0.00581096375139595,
    ascendingNodeRateDegPerDay: 2.04486780781651,
    tier: "librator",
    maxCalibrationSeparationDeg: 38.73,
    holdoutSeparationDeg: 6.354,
  },
  // SAT415 Laplace @ 2000-01-01.5; quoted: a=151500. e=0.007 ω=11.1 M=111.7 i=0.2 node=159.9 P=0.697353 Pap=0.240 Pnode=0.482 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=anom signs=(+1,-1)
  "Janus": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 151500, eccentricity: 0.007, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 11.1, ascendingNodeAtEpochDeg: 159.9,
    meanAnomalyAtEpochDeg: 112.847638918,
    meanAnomalyRateDegPerDay: 516.237830768635,
    argPeriapsisRateDegPerDay: 4.10275145831581,
    ascendingNodeRateDegPerDay: -2.04666684573504,
    tier: "librator",
    maxCalibrationSeparationDeg: 28.29,
    holdoutSeparationDeg: 13.88,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=186000. e=0.020 ω=160.4 M=275.3 i=1.6 node=66.2 P=0.942422 Pap=0.493 Pnode=0.986 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=lam signs=(+1,+1)
  "Mimas": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 186000, eccentricity: 0.02, inclinationDeg: 1.6,
    argPeriapsisAtEpochDeg: 160.4, ascendingNodeAtEpochDeg: 66.2,
    meanAnomalyAtEpochDeg: 324.620008678,
    meanAnomalyRateDegPerDay: 378.995615126462,
    argPeriapsisRateDegPerDay: 1.99520137478702,
    ascendingNodeRateDegPerDay: 0.998620157623877,
    tier: "librator",
    maxCalibrationSeparationDeg: 28.91,
    holdoutSeparationDeg: 25.9,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=238400. e=0.005 ω=119.5 M=57.0 i=0.0 node=0.0 P=1.370218 Pap=2.916 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: model=lam signs=(+1,-1)
  "Enceladus": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 238400, eccentricity: 0.005, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 119.5, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 62.4519301663,
    meanAnomalyRateDegPerDay: 262.393909381362,
    argPeriapsisRateDegPerDay: 0.338006270016309,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.637,
    holdoutSeparationDeg: 0.4256,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=295000. e=0.001 ω=335.3 M=0.0 i=1.1 node=273.0 P=1.887802 Pap=0.005 Pnode=4.982 pole=(40.6,83.5) tilt=0.0
  // calibration: model=lam signs=(+1,-1)
  "Tethys": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 295000, eccentricity: 0.001, inclinationDeg: 1.1,
    argPeriapsisAtEpochDeg: 335.3, ascendingNodeAtEpochDeg: 273,
    meanAnomalyAtEpochDeg: 298.824028741,
    meanAnomalyRateDegPerDay: -6.22945405517155,
    argPeriapsisRateDegPerDay: 197.125256673511,
    ascendingNodeRateDegPerDay: -0.197837471571167,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 2.679,
    holdoutSeparationDeg: 2.915,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=295000. e=0.001 ω=221.6 M=-0.0 i=1.5 node=326.6 P=1.887803 Pap=0.005 Pnode=4.983 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=lam signs=(-1,-1)
  "Calypso": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 295000, eccentricity: 0.001, inclinationDeg: 1.5,
    argPeriapsisAtEpochDeg: 221.6, ascendingNodeAtEpochDeg: 326.6,
    meanAnomalyAtEpochDeg: 300.18961645,
    meanAnomalyRateDegPerDay: 388.02091857355,
    argPeriapsisRateDegPerDay: -197.125256673511,
    ascendingNodeRateDegPerDay: -0.197470859098131,
    tier: "librator",
    maxCalibrationSeparationDeg: 4.501,
    holdoutSeparationDeg: 2.615,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=295000. e=0.001 ω=66.2 M=360.0 i=1.2 node=242.1 P=1.887802 Pap=0.005 Pnode=4.982 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=lam signs=(+1,+1)
  "Telesto": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 295000, eccentricity: 0.001, inclinationDeg: 1.2,
    argPeriapsisAtEpochDeg: 66.2, ascendingNodeAtEpochDeg: 242.1,
    meanAnomalyAtEpochDeg: 297.883458192,
    meanAnomalyRateDegPerDay: -6.62512899831389,
    argPeriapsisRateDegPerDay: 197.125256673511,
    ascendingNodeRateDegPerDay: 0.198092784248004,
    tier: "librator",
    maxCalibrationSeparationDeg: 2.655,
    holdoutSeparationDeg: 1.252,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=377700. e=0.002 ω=116.0 M=212.0 i=0.0 node=0.0 P=2.736916 Pap=11.698 Pnode=0.000 pole=(40.6,83.5) tilt=0.0
  // calibration: model=lam signs=(-1,-1)
  "Dione": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 377700, eccentricity: 0.002, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 116, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 60.5384576676,
    meanAnomalyRateDegPerDay: 131.619166061299,
    argPeriapsisRateDegPerDay: -0.0842559654101177,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.8269,
    holdoutSeparationDeg: 0.787,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=377600. e=0.007 ω=194.3 M=-64.5 i=0.2 node=260.8 P=2.736916 Pap=5.825 Pnode=11.707 pole=(40.6,83.5) tilt=0.0
  // calibration: seed=lam signs=(+1,+1)
  "Helene": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 377600, eccentricity: 0.007, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 194.3, ascendingNodeAtEpochDeg: 260.8,
    meanAnomalyAtEpochDeg: 134.120193939,
    meanAnomalyRateDegPerDay: 131.281512675102,
    argPeriapsisRateDegPerDay: 0.169243795147588,
    ascendingNodeRateDegPerDay: 0.0850434014999236,
    tier: "librator",
    maxCalibrationSeparationDeg: 15.03,
    holdoutSeparationDeg: 14.71,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=527200. e=0.001 ω=44.3 M=31.5 i=0.3 node=133.7 P=4.517503 Pap=33.939 Pnode=35.775 pole=(40.6,83.5) tilt=0.0
  // calibration: model=lam signs=(+1,+1)
  "Rhea": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.6, poleDecDeg: 83.5,
    epochJdTdb: 2451545,
    aKm: 527200, eccentricity: 0.001, inclinationDeg: 0.3,
    argPeriapsisAtEpochDeg: 44.3, ascendingNodeAtEpochDeg: 133.7,
    meanAnomalyAtEpochDeg: 234.21101585,
    meanAnomalyRateDegPerDay: 79.6334493464429,
    argPeriapsisRateDegPerDay: 0.0290411115049812,
    ascendingNodeRateDegPerDay: 0.0275506997447255,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.5507,
    holdoutSeparationDeg: 0.1316,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=1221900. e=0.029 ω=78.3 M=11.7 i=0.3 node=78.6 P=15.945448 Pap=346.680 Pnode=687.370 pole=(36.4,84.0) tilt=0.6
  // calibration: model=lam signs=(+1,+1)
  "Titan": {
    parentPlanet: "Saturn",
    poleRaDeg: 36.4, poleDecDeg: 84,
    epochJdTdb: 2451545,
    aKm: 1221900, eccentricity: 0.029, inclinationDeg: 0.3,
    argPeriapsisAtEpochDeg: 78.3, ascendingNodeAtEpochDeg: 78.6,
    meanAnomalyAtEpochDeg: 217.698270217,
    meanAnomalyRateDegPerDay: 22.5726992475929,
    argPeriapsisRateDegPerDay: 0.00284304339266054,
    ascendingNodeRateDegPerDay: 0.00143390936957906,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 5.474,
    holdoutSeparationDeg: 4.079,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=1481500. e=0.105 ω=214.0 M=122.9 i=0.6 node=87.1 P=21.276658 Pap=20.843 Pnode=257.625 pole=(40.2,83.6) tilt=0.1
  // calibration: seed=lam signs=(+1,-1)
  "Hyperion": {
    parentPlanet: "Saturn",
    poleRaDeg: 40.2, poleDecDeg: 83.6,
    epochJdTdb: 2451545,
    aKm: 1481500, eccentricity: 0.105, inclinationDeg: 0.6,
    argPeriapsisAtEpochDeg: 214, ascendingNodeAtEpochDeg: 87.1,
    meanAnomalyAtEpochDeg: 9.48545983774,
    meanAnomalyRateDegPerDay: 16.8764881900047,
    argPeriapsisRateDegPerDay: 0.046347086327714,
    ascendingNodeRateDegPerDay: -0.00398982445848927,
    tier: "librator",
    maxCalibrationSeparationDeg: 23.01,
    holdoutSeparationDeg: 14.19,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=3561700. e=0.028 ω=254.5 M=74.8 i=7.6 node=86.5 P=79.331002 Pap=1662.900 Pnode=3130.302 pole=(288.7,78.9) tilt=14.8
  // calibration: model=lam signs=(+1,-1)
  "Iapetus": {
    parentPlanet: "Saturn",
    poleRaDeg: 288.7, poleDecDeg: 78.9,
    epochJdTdb: 2451545,
    aKm: 3561700, eccentricity: 0.028, inclinationDeg: 7.6,
    argPeriapsisAtEpochDeg: 254.5, ascendingNodeAtEpochDeg: 86.5,
    meanAnomalyAtEpochDeg: 219.87782031,
    meanAnomalyRateDegPerDay: 4.5376706316108,
    argPeriapsisRateDegPerDay: 0.00059271530661348,
    ascendingNodeRateDegPerDay: -0.000314866196094676,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 1.672,
    holdoutSeparationDeg: 1.27,
  },
  // SAT441 Laplace @ 2000-01-01.5; quoted: a=12929400. e=0.164 ω=240.3 M=308.0 i=175.2 node=192.7 P=550.303910 Pap=468.321 Pnode=741.483 pole=(276.0,67.5) tilt=26.7
  // calibration: seed=anom signs=(+1,+1) dense-epochs
  "Phoebe": {
    parentPlanet: "Saturn",
    poleRaDeg: 276, poleDecDeg: 67.5,
    epochJdTdb: 2451545,
    aKm: 12929400, eccentricity: 0.164, inclinationDeg: 175.2,
    argPeriapsisAtEpochDeg: 240.3, ascendingNodeAtEpochDeg: 192.7,
    meanAnomalyAtEpochDeg: 108.579322222,
    meanAnomalyRateDegPerDay: 0.653821449315166,
    argPeriapsisRateDegPerDay: 0.00105186312964957,
    ascendingNodeRateDegPerDay: 0.00132967973161134,
    tier: "fitted",
    maxCalibrationSeparationDeg: 21.28,
    holdoutSeparationDeg: 7.113,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=49755. e=0.000 ω=0.0 M=287.4 i=0.2 node=1.1 P=0.3347 Pap=0.0 Pnode=0.6 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(+1,+1) dense-epochs
  "Cordelia": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 49755, eccentricity: 0, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 1.1,
    meanAnomalyAtEpochDeg: 276.719181263,
    meanAnomalyRateDegPerDay: 1075.33014639986,
    argPeriapsisRateDegPerDay: 0.00198699467569062,
    ascendingNodeRateDegPerDay: -0.82135523613963,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.3502,
    holdoutSeparationDeg: 0.1918,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=53765. e=0.011 ω=19.3 M=213.4 i=0.2 node=151.6 P=0.3764 Pap=0.4 Pnode=0.8 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(+1,-1) dense-epochs
  "Ophelia": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 53765, eccentricity: 0.011, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 19.3, ascendingNodeAtEpochDeg: 151.6,
    meanAnomalyAtEpochDeg: 203.850617543,
    meanAnomalyRateDegPerDay: 960.175345377338,
    argPeriapsisRateDegPerDay: -2.46381462059335,
    ascendingNodeRateDegPerDay: -1.23191962936978,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.156,
    holdoutSeparationDeg: 0.9465,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=59170. e=0.006 ω=328.0 M=109.1 i=2.3 node=272.5 P=0.4347 Pap=0.5 Pnode=1.1 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Bianca": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 59170, eccentricity: 0.006, inclinationDeg: 2.3,
    argPeriapsisAtEpochDeg: 328, ascendingNodeAtEpochDeg: 272.5,
    meanAnomalyAtEpochDeg: 100.874282186,
    meanAnomalyRateDegPerDay: 831.252587991644,
    argPeriapsisRateDegPerDay: -1.96507606584857,
    ascendingNodeRateDegPerDay: -0.900600684130526,
    tier: "fitted",
    maxCalibrationSeparationDeg: 4.431,
    holdoutSeparationDeg: 1.465,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=61770. e=0.004 ω=87.9 M=0.5 i=1.8 node=308.2 P=0.4639 Pap=0.6 Pnode=1.2 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Cressida": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 61770, eccentricity: 0.004, inclinationDeg: 1.8,
    argPeriapsisAtEpochDeg: 87.9, ascendingNodeAtEpochDeg: 308.2,
    meanAnomalyAtEpochDeg: 352.76607839,
    meanAnomalyRateDegPerDay: 777.403535244689,
    argPeriapsisRateDegPerDay: -0.00307267598643091,
    ascendingNodeRateDegPerDay: -0.818308578788092,
    tier: "fitted",
    maxCalibrationSeparationDeg: 3.046,
    holdoutSeparationDeg: 0.5102,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=64362. e=0.006 ω=274.9 M=319.8 i=3.0 node=141.0 P=0.4931 Pap=0.7 Pnode=1.4 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Juliet": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 64362, eccentricity: 0.006, inclinationDeg: 3,
    argPeriapsisAtEpochDeg: 274.9, ascendingNodeAtEpochDeg: 141,
    meanAnomalyAtEpochDeg: 312.44816145,
    meanAnomalyRateDegPerDay: 729.421009937095,
    argPeriapsisRateDegPerDay: 1.4062312001751,
    ascendingNodeRateDegPerDay: -0.703377203650395,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.417,
    holdoutSeparationDeg: 0.1094,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=66101. e=0.004 ω=31.6 M=310.1 i=2.7 node=146.7 P=0.5132 Pap=0.8 Pnode=1.6 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=lam signs=(-1,-1) dense-epochs
  "Portia": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 66101, eccentricity: 0.004, inclinationDeg: 2.7,
    argPeriapsisAtEpochDeg: 31.6, ascendingNodeAtEpochDeg: 146.7,
    meanAnomalyAtEpochDeg: 303.131741787,
    meanAnomalyRateDegPerDay: 703.340675561534,
    argPeriapsisRateDegPerDay: -1.23547907851082,
    ascendingNodeRateDegPerDay: -0.612414350457521,
    tier: "fitted",
    maxCalibrationSeparationDeg: 4.233,
    holdoutSeparationDeg: 0.3672,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=69930. e=0.003 ω=231.8 M=287.7 i=1.7 node=330.0 P=0.5583 Pap=0.9 Pnode=1.9 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=lam signs=(+1,+1) dense-epochs
  "Rosalind": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 69930, eccentricity: 0.003, inclinationDeg: 1.7,
    argPeriapsisAtEpochDeg: 231.8, ascendingNodeAtEpochDeg: 330,
    meanAnomalyAtEpochDeg: 281.222636668,
    meanAnomalyRateDegPerDay: 643.790325472056,
    argPeriapsisRateDegPerDay: 1.09805276238214,
    ascendingNodeRateDegPerDay: -0.262512337978854,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.716,
    holdoutSeparationDeg: 2.19,
  },
  // URA184 Laplace @ 2025-01-01.0; quoted: a=86007. e=0.009 ω=337.0 M=264.1 i=1.1 node=111.2 P=0.7618 Pap=1.9 Pnode=3.9 pole=(77.3,15.2) tilt=180.0
  // calibration: seed=anom signs=(-1,+1) dense-epochs
  "Puck": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.3, poleDecDeg: 15.2,
    epochJdTdb: 2460676.5,
    aKm: 86007, eccentricity: 0.009, inclinationDeg: 1.1,
    argPeriapsisAtEpochDeg: 337, ascendingNodeAtEpochDeg: 111.2,
    meanAnomalyAtEpochDeg: 259.353384368,
    meanAnomalyRateDegPerDay: 472.811105277007,
    argPeriapsisRateDegPerDay: -0.519309824216155,
    ascendingNodeRateDegPerDay: 0.252477845994569,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.681,
    holdoutSeparationDeg: 1.524,
  },
  // URA182 equatorial @ 2000-01-01.5; quoted: a=129846. e=0.001 ω=154.8 M=73.0 i=4.4 node=100.9 P=1.413479 Pap=8.939 Pnode=17.787 pole=(—,—) tilt=—
  // calibration: model=lam signs=(-1,-1)
  "Miranda": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.311, poleDecDeg: 15.175,
    epochJdTdb: 2451545,
    aKm: 129846, eccentricity: 0.001, inclinationDeg: 4.4,
    argPeriapsisAtEpochDeg: 154.8, ascendingNodeAtEpochDeg: 100.9,
    meanAnomalyAtEpochDeg: 71.9078363313,
    meanAnomalyRateDegPerDay: 254.856405259121,
    argPeriapsisRateDegPerDay: -0.110261358470473,
    ascendingNodeRateDegPerDay: -0.0554127330841377,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 2.323,
    holdoutSeparationDeg: 0.3777,
  },
  // URA182 equatorial @ 2000-01-01.5; quoted: a=190929. e=0.001 ω=9.6 M=193.5 i=0.0 node=0.0 P=2.520379 Pap=28.901 Pnode=0.000 pole=(—,—) tilt=—
  // calibration: model=lam signs=(-1,-1)
  "Ariel": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.311, poleDecDeg: 15.175,
    epochJdTdb: 2451545,
    aKm: 190929, eccentricity: 0.001, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 9.6, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 193.716557192,
    meanAnomalyRateDegPerDay: 142.869764362835,
    argPeriapsisRateDegPerDay: -0.0341035356343226,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.4028,
    holdoutSeparationDeg: 0.4645,
  },
  // URA182 equatorial @ 2000-01-01.5; quoted: a=265986. e=0.004 ω=183.4 M=253.0 i=0.1 node=174.8 P=4.144177 Pap=64.126 Pnode=129.745 pole=(—,—) tilt=—
  // calibration: model=lam signs=(+1,-1)
  "Umbriel": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.311, poleDecDeg: 15.175,
    epochJdTdb: 2451545,
    aKm: 265986, eccentricity: 0.004, inclinationDeg: 0.1,
    argPeriapsisAtEpochDeg: 183.4, ascendingNodeAtEpochDeg: 174.8,
    meanAnomalyAtEpochDeg: 252.994664844,
    meanAnomalyRateDegPerDay: 86.8611029893298,
    argPeriapsisRateDegPerDay: 0.0153701506934404,
    ascendingNodeRateDegPerDay: -0.0075966417462527,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.1714,
    holdoutSeparationDeg: 0.07611,
  },
  // URA182 equatorial @ 2000-01-01.5; quoted: a=436298. e=0.002 ω=184.0 M=68.1 i=0.1 node=29.5 P=8.705869 Pap=579.928 Pnode=1644.649 pole=(—,—) tilt=—
  // calibration: model=lam signs=(+1,+1)
  "Titania": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.311, poleDecDeg: 15.175,
    epochJdTdb: 2451545,
    aKm: 436298, eccentricity: 0.002, inclinationDeg: 0.1,
    argPeriapsisAtEpochDeg: 184, ascendingNodeAtEpochDeg: 29.5,
    meanAnomalyAtEpochDeg: 68.157052688,
    meanAnomalyRateDegPerDay: 41.3491159160518,
    argPeriapsisRateDegPerDay: 0.0016995666416651,
    ascendingNodeRateDegPerDay: 0.000599292787316659,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.2582,
    holdoutSeparationDeg: 0.07539,
  },
  // URA182 equatorial @ 2000-01-01.5; quoted: a=583511. e=0.002 ω=132.2 M=143.6 i=0.1 node=76.8 P=13.463237 Pap=158.604 Pnode=192.798 pole=(—,—) tilt=—
  // calibration: model=lam signs=(-1,-1)
  "Oberon": {
    parentPlanet: "Uranus",
    poleRaDeg: 77.311, poleDecDeg: 15.175,
    epochJdTdb: 2451545,
    aKm: 583511, eccentricity: 0.002, inclinationDeg: 0.1,
    argPeriapsisAtEpochDeg: 132.2, ascendingNodeAtEpochDeg: 76.8,
    meanAnomalyAtEpochDeg: 143.474038619,
    meanAnomalyRateDegPerDay: 26.7508098385907,
    argPeriapsisRateDegPerDay: -0.00621438477823735,
    ascendingNodeRateDegPerDay: -0.00511222255089553,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.196,
    holdoutSeparationDeg: 0.1755,
  },
  // URA117 ecliptic @ 2020-01-01.0; quoted: a=7167000. e=0.200 ω=349.7 M=241.2 i=141.4 node=174.9 P=580. Pap=8795. Pnode=6483. pole=(—,—) tilt=—
  // calibration: seed=lam signs=(-1,-1) dense-epochs
  "Caliban": {
    parentPlanet: "Uranus",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2458849.5,
    aKm: 7167000, eccentricity: 0.2, inclinationDeg: 141.4,
    argPeriapsisAtEpochDeg: 349.7, ascendingNodeAtEpochDeg: 174.9,
    meanAnomalyAtEpochDeg: 241.685060443,
    meanAnomalyRateDegPerDay: 0.620964103498821,
    argPeriapsisRateDegPerDay: -0.0000572135304927548,
    ascendingNodeRateDegPerDay: -0.000152943336120246,
    tier: "fitted",
    maxCalibrationSeparationDeg: 24.45,
    holdoutSeparationDeg: 2.972,
  },
  // URA117 ecliptic @ 2020-01-01.0; quoted: a=12193200. e=0.520 ω=25.4 M=332.1 i=157.0 node=267.1 P=1286. Pap=1394. Pnode=1863. pole=(—,—) tilt=—
  // calibration: seed=lam signs=(+1,+1)
  "Sycorax": {
    parentPlanet: "Uranus",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2458849.5,
    aKm: 12193200, eccentricity: 0.52, inclinationDeg: 157,
    argPeriapsisAtEpochDeg: 25.4, ascendingNodeAtEpochDeg: 267.1,
    meanAnomalyAtEpochDeg: 144.682474515,
    meanAnomalyRateDegPerDay: 0.278701689325902,
    argPeriapsisRateDegPerDay: 0.00163618343626409,
    ascendingNodeRateDegPerDay: 0.00108909891259851,
    tier: "fitted",
    maxCalibrationSeparationDeg: 4.642,
    holdoutSeparationDeg: 5.498,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=48200. e=0.000 ω=0.0 M=89.7 i=4.7 node=41.4 P=0.293980 Pap=0.000 Pnode=0.575 pole=(299.7,42.7) tilt=0.4
  // calibration: seed=anom signs=(+1,-1)
  "Naiad": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.7, poleDecDeg: 42.7,
    epochJdTdb: 2451545,
    aKm: 48200, eccentricity: 0, inclinationDeg: 4.7,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 41.4,
    meanAnomalyAtEpochDeg: 86.5670094959,
    meanAnomalyRateDegPerDay: 1224.5731002109,
    argPeriapsisRateDegPerDay: -0.0005449297,
    ascendingNodeRateDegPerDay: -1.71413266672619,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.4192,
    holdoutSeparationDeg: 0.6913,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=50100. e=0.000 ω=0.0 M=165.7 i=0.2 node=130.6 P=0.311078 Pap=0.000 Pnode=0.654 pole=(299.7,42.7) tilt=0.4
  // calibration: model=anom signs=(+1,-1)
  "Thalassa": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.7, poleDecDeg: 42.7,
    epochJdTdb: 2451545,
    aKm: 50100, eccentricity: 0, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 130.6,
    meanAnomalyAtEpochDeg: 162.78043937,
    meanAnomalyRateDegPerDay: 1157.26602331248,
    argPeriapsisRateDegPerDay: 0,
    ascendingNodeRateDegPerDay: -1.50707382777914,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 4.993,
    holdoutSeparationDeg: 3.34,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=52500. e=0.000 ω=0.0 M=125.1 i=0.0 node=0.0 P=0.334656 Pap=0.000 Pnode=0.000 pole=(299.7,42.7) tilt=0.4
  // calibration: seed=lam signs=(+1,-1)
  "Despina": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.7, poleDecDeg: 42.7,
    epochJdTdb: 2451545,
    aKm: 52500, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 122.199326171,
    meanAnomalyRateDegPerDay: 1075.73149741824,
    argPeriapsisRateDegPerDay: 0.0002779,
    ascendingNodeRateDegPerDay: 0.00129266709759379,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.3259,
    holdoutSeparationDeg: 0.2423,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=62000. e=0.000 ω=0.0 M=86.7 i=0.0 node=0.0 P=0.428744 Pap=0.000 Pnode=0.000 pole=(299.8,43.1) tilt=0.4
  // calibration: seed=lam signs=(+1,-1)
  "Galatea": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.8, poleDecDeg: 43.1,
    epochJdTdb: 2451545,
    aKm: 62000, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 83.6959423716,
    meanAnomalyRateDegPerDay: 839.661896143153,
    argPeriapsisRateDegPerDay: -0.00005121,
    ascendingNodeRateDegPerDay: -0.00054011,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.3051,
    holdoutSeparationDeg: 0.09182,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=73500. e=0.001 ω=247.3 M=165.5 i=0.2 node=312.0 P=0.554989 Pap=1.257 Pnode=2.514 pole=(299.8,43.1) tilt=0.4
  // calibration: seed=anom signs=(+1,-1)
  "Larissa": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.8, poleDecDeg: 43.1,
    epochJdTdb: 2451545,
    aKm: 73500, eccentricity: 0.001, inclinationDeg: 0.2,
    argPeriapsisAtEpochDeg: 247.3, ascendingNodeAtEpochDeg: 312,
    meanAnomalyAtEpochDeg: 162.431471871,
    meanAnomalyRateDegPerDay: 648.661505002802,
    argPeriapsisRateDegPerDay: 0.787394446339493,
    ascendingNodeRateDegPerDay: -0.394804829222142,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.3419,
    holdoutSeparationDeg: 0.05849,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=117600. e=0.000 ω=0.0 M=276.8 i=0.0 node=0.0 P=1.122315 Pap=0.000 Pnode=0.000 pole=(299.8,42.6) tilt=0.9
  // calibration: model=lam signs=(+1,-1)
  "Proteus": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.8, poleDecDeg: 42.6,
    epochJdTdb: 2451545,
    aKm: 117600, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 273.76023326,
    meanAnomalyRateDegPerDay: 320.765560470991,
    argPeriapsisRateDegPerDay: 0,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 1.094,
    holdoutSeparationDeg: 0.7488,
  },
  // NEP097 Laplace @ 2000-01-01.5; quoted: a=354800. e=0.000 ω=0.0 M=63.0 i=157.3 node=178.1 P=5.876994 Pap=0.000 Pnode=340.379 pole=(299.8,43.1) tilt=0.4
  // calibration: seed=anom signs=(+1,-1)
  "Triton": {
    parentPlanet: "Neptune",
    poleRaDeg: 299.8, poleDecDeg: 43.1,
    epochJdTdb: 2451545,
    aKm: 354800, eccentricity: 0, inclinationDeg: 157.3,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 178.1,
    meanAnomalyAtEpochDeg: 58.9608536893,
    meanAnomalyRateDegPerDay: 61.2558052637113,
    argPeriapsisRateDegPerDay: 0.00272828247342029,
    ascendingNodeRateDegPerDay: 0.00125197222644326,
    tier: "fitted",
    maxCalibrationSeparationDeg: 0.3911,
    holdoutSeparationDeg: 0.2515,
  },
  // NEP105 ecliptic @ 2020-01-01.0; quoted: a=5513900. e=0.751 ω=296.8 M=318.5 i=5.1 node=319.5 P=360.133039 Pap=7990.433 Pnode=9426.334 pole=(—,—) tilt=—
  // calibration: model=anom signs=(-1,+1)
  "Nereid": {
    parentPlanet: "Neptune",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2458849.5,
    aKm: 5513900, eccentricity: 0.751, inclinationDeg: 5.1,
    argPeriapsisAtEpochDeg: 296.8, ascendingNodeAtEpochDeg: 319.5,
    meanAnomalyAtEpochDeg: 319.445538915,
    meanAnomalyRateDegPerDay: 0.999630583741027,
    argPeriapsisRateDegPerDay: -0.000123350797555972,
    ascendingNodeRateDegPerDay: 0.000104560933589618,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.5829,
    holdoutSeparationDeg: 0.4061,
  },
  // NEP104 ecliptic @ 2020-01-01.0; quoted: a=16590500. e=0.521 ω=157.9 M=135.8 i=119.6 node=198.5 P=1879. Pap=5395. Pnode=5156. pole=(—,—) tilt=—
  // calibration: seed=anom signs=(-1,-1) dense-epochs
  "Halimede": {
    parentPlanet: "Neptune",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2458849.5,
    aKm: 16590500, eccentricity: 0.521, inclinationDeg: 119.6,
    argPeriapsisAtEpochDeg: 157.9, ascendingNodeAtEpochDeg: 198.5,
    meanAnomalyAtEpochDeg: 166.553080708,
    meanAnomalyRateDegPerDay: 0.191698243746679,
    argPeriapsisRateDegPerDay: 0.000183702645573226,
    ascendingNodeRateDegPerDay: -0.000191281232460736,
    tier: "fitted",
    maxCalibrationSeparationDeg: 64.31,
    holdoutSeparationDeg: 35.94,
  },
  // NEP104 ecliptic @ 2020-01-01.0; quoted: a=49897800. e=0.455 ω=89.8 M=13.8 i=128.4 node=55.4 P=9805. Pap=- Pnode=1116. pole=(—,—) tilt=—
  // calibration: seed=anom signs=(+1,+1) dense-epochs
  "Neso": {
    parentPlanet: "Neptune",
    poleRaDeg: null, poleDecDeg: null,
    epochJdTdb: 2458849.5,
    aKm: 49897800, eccentricity: 0.455, inclinationDeg: 128.4,
    argPeriapsisAtEpochDeg: 89.8, ascendingNodeAtEpochDeg: 55.4,
    meanAnomalyAtEpochDeg: 143.522831344,
    meanAnomalyRateDegPerDay: 0.0354309026007139,
    argPeriapsisRateDegPerDay: -0.00104059141871458,
    ascendingNodeRateDegPerDay: 0.00091316747326842,
    tier: "fitted",
    maxCalibrationSeparationDeg: 90.43,
    holdoutSeparationDeg: 18.49,
  },
  // PLU060 equatorial @ 2000-01-01.5; quoted: a=19600. e=0.000 ω=0.0 M=304.1 i=0.0 node=0.0 P=6.387222 Pap=- Pnode=- pole=(—,—) tilt=—
  // calibration: model=lam signs=(+1,-1)
  "Charon": {
    parentPlanet: "Pluto",
    poleRaDeg: 132.993, poleDecDeg: -6.163,
    epochJdTdb: 2451545,
    aKm: 19600, eccentricity: 0, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 0, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 304.130492942,
    meanAnomalyRateDegPerDay: 56.3625313164315,
    argPeriapsisRateDegPerDay: 0,
    ascendingNodeRateDegPerDay: 0,
    tier: "verbatim",
    maxCalibrationSeparationDeg: 0.08208,
    holdoutSeparationDeg: 0.07528,
  },
  // PLU060 equatorial @ 2000-01-01.5; quoted: a=43200. e=0.025 ω=322.5 M=358.1 i=0.0 node=0.0 P=20.16 Pap=- Pnode=- pole=(—,—) tilt=—
  // calibration: seed=lam signs=(+1,-1) dense-epochs
  "Styx": {
    parentPlanet: "Pluto",
    poleRaDeg: 132.993, poleDecDeg: -6.163,
    epochJdTdb: 2451545,
    aKm: 43200, eccentricity: 0.025, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 322.5, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 233.334792639,
    meanAnomalyRateDegPerDay: 17.8559523809511,
    argPeriapsisRateDegPerDay: -0.0000132229,
    ascendingNodeRateDegPerDay: -0.00101325783774786,
    tier: "fitted",
    maxCalibrationSeparationDeg: 9.578,
    holdoutSeparationDeg: 4.897,
  },
  // PLU060 equatorial @ 2000-01-01.5; quoted: a=49300. e=0.015 ω=31.4 M=338.2 i=0.0 node=0.0 P=24.85 Pap=- Pnode=- pole=(—,—) tilt=—
  // calibration: seed=lam signs=(+1,-1)
  "Nix": {
    parentPlanet: "Pluto",
    poleRaDeg: 132.993, poleDecDeg: -6.163,
    epochJdTdb: 2451545,
    aKm: 49300, eccentricity: 0.015, inclinationDeg: 0,
    argPeriapsisAtEpochDeg: 31.4, ascendingNodeAtEpochDeg: 0,
    meanAnomalyAtEpochDeg: 57.6105835145,
    meanAnomalyRateDegPerDay: 14.486921529175,
    argPeriapsisRateDegPerDay: -0.000530667700000001,
    ascendingNodeRateDegPerDay: -0.00171103038944242,
    tier: "fitted",
    maxCalibrationSeparationDeg: 4.608,
    holdoutSeparationDeg: 0.5151,
  },
  // PLU060 equatorial @ 2000-01-01.5; quoted: a=58300. e=0.010 ω=32.1 M=276.1 i=0.4 node=314.3 P=32.17 Pap=- Pnode=9 pole=(—,—) tilt=—
  // calibration: seed=lam signs=(+1,-1)
  "Kerberos": {
    parentPlanet: "Pluto",
    poleRaDeg: 132.993, poleDecDeg: -6.163,
    epochJdTdb: 2451545,
    aKm: 58300, eccentricity: 0.01, inclinationDeg: 0.4,
    argPeriapsisAtEpochDeg: 32.1, ascendingNodeAtEpochDeg: 314.3,
    meanAnomalyAtEpochDeg: 283.7666821,
    meanAnomalyRateDegPerDay: 11.3000642335369,
    argPeriapsisRateDegPerDay: 0.000804179000000001,
    ascendingNodeRateDegPerDay: -0.109514031485284,
    tier: "fitted",
    maxCalibrationSeparationDeg: 4.846,
    holdoutSeparationDeg: 4.396,
  },
  // PLU060 equatorial @ 2000-01-01.5; quoted: a=65200. e=0.009 ω=139.3 M=335.0 i=0.3 node=114.3 P=38.20 Pap=- Pnode=14 pole=(—,—) tilt=—
  // calibration: seed=lam signs=(+1,+1)
  "Hydra": {
    parentPlanet: "Pluto",
    poleRaDeg: 132.993, poleDecDeg: -6.163,
    epochJdTdb: 2451545,
    aKm: 65200, eccentricity: 0.009, inclinationDeg: 0.3,
    argPeriapsisAtEpochDeg: 139.3, ascendingNodeAtEpochDeg: 114.3,
    meanAnomalyAtEpochDeg: 341.196426678,
    meanAnomalyRateDegPerDay: 9.35368189225011,
    argPeriapsisRateDegPerDay: -0.0005180669,
    ascendingNodeRateDegPerDay: 0.0704018773833969,
    tier: "fitted",
    maxCalibrationSeparationDeg: 2.484,
    holdoutSeparationDeg: 0.3693,
  },
};
